# Generated by Django 2.0 on 2019-03-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apihouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('civil_no', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=500)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apihouse.Country'),
        ),
    ]
